---
- hosts: all
  become: true
  tasks:
   - name: install Apache httpd
     yum:
       name: httpd
       state:  latest
   - name: install php support for Apache
     yum:
       name: php
       state:  latest
